### ISSUE TITLE
Please update - add xt1562 reteu ota 24.41.33 (MPD24.65-33) & full reteu stock rom MPD24.65-33

### ISSUE THREAD

**Issue by octav-s** [motoxplay/stock#4]
MPD24.65-33 ota link: [link](http://forum.xda-developers.com/moto-x-play/help/marshmallow-europe-update-t3310489/post65420685#post65420685)

full reteu MPD24.65-33: [link](http://forum.xda-developers.com/moto-x-play/general/official-stock-firmwares-added-xt1562-t3195364/post65423306#post65423306)

**Comment by mfonville** [comment]
@octav-s I will add you to team, than you can directly upload to the releases :-)
Clearly you are much better up to date with the latest images than I am ;-)

I assume you know how GitHub and their releases-system works, otherwise just drop me a line.
Please upload only official images and try to stick to the naming and structuring scheme (or feel free to improve it if possible)

**Comment by mfonville** [comment]
I uploaded them.

**Comment by octav-s** [comment]
Sorry for not uploading them in time, i'm currently in the process of job
hunting, I was planning on doing it today. I will upload the future ones.
Thanx.

**Comment by mfonville** [comment]
@octav-s ok, thanks and welcome :-)
